[package]
name = "ssh-auth-github"
version = "0.1.0"
authors = ["Erik Dal√©n <erik.gustav.dalen@gmail.com>"]

[dependencies]
jsonwebtoken = "4.0.1"
serde_json = "1.0.16"
reqwest = "0.8.5"
serde_derive = "1.0.43"
serde = "1.0.43"
