[package]
name = "ssh-auth-github"
version = "0.1.0"
authors = ["Erik DalÃ©n <erik.gustav.dalen@gmail.com>"]

[dependencies]
reqwest = "0.9.8"
serde_json = "1.0.36"
serde_derive = "1.0.85"
serde = "1.0.85"
