[package]
name = "ssh-auth-github"
version = "0.1.0"
authors = ["Erik DalÃ©n <erik.gustav.dalen@gmail.com>"]

[dependencies]
reqwest = "0.8.5"
serde_json = "1.0.33"
serde_derive = "1.0.81"
serde = "1.0.81"
