[package]
name = "ssh-auth-github"
version = "0.1.0"
authors = ["Erik DalÃ©n <erik.gustav.dalen@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.21"
serde_json = "1.0.41"
serde_derive = "1.0.101"
serde = "1.0.101"
